GET http://localhost:3000/ HTTP/1.1
###
GET http://localhost:3000/nextTurn/suscribe HTTP/1.1
###
GET http://localhost:3000/BD/Turno HTTP/1.1
###
GET http://localhost:3000/BD/TT HTTP/1.1


###
POST http://localhost:3000/newTurn HTTP/1.1
content-type: application/json

{  
    "cola": "3", 
    "turno" : "addc"
    }

###
POST http://localhost:3000/nextTurn HTTP/1.1
content-type: application/json

{   
     "cola": "3"
     }
###
POST http://localhost:3000/createTurn HTTP/1.1
content-type: application/json

{  
    "cola": "1"
    }
###
POST http://localhost:3000/BD/Turno HTTP/1.1
content-type: application/json

{

}
###
POST http://localhost:3000/BD/TT HTTP/1.1
content-type: application/json

{

}