GET http://localhost:3000/ HTTP/1.1

###

GET http://localhost:3000/nextTurn/suscribe HTTP/1.1

###

POST http://localhost:3000/newTurn HTTP/1.1
content-type: application/json

{
    "cola": "1",
    "turno" : "6666"
}
###
POST http://localhost:3000/nextTurn HTTP/1.1
content-type: application/json

{
    "cola": "1"
}
###
POST http://localhost:3000/createTurn HTTP/1.1
content-type: application/json

{
    "cola": "1"
}
###
POST http://localhost:3000/BD HTTP/1.1
content-type: application/json

{
}